// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedBerryCorporate.Data;

#nullable disable

namespace RedBerryCorporate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710135723_AddUsermanagement")]
    partial class AddUsermanagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RedBerryCorporate.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlogDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MetaDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OpenCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReadTime")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("RedBerryCorporate.Models.BlueprintSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ambition")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("BusinessStage")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CorporateScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ExposedLayer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FinancialScore")
                        .HasColumnType("int");

                    b.Property<string>("ImprovementLayers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegacyScore")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("MarketScore")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("OverallStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PatternsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecommendedPathway")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ReviewMethod")
                        .HasColumnType("int");

                    b.Property<string>("StrongestLayer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int");

                    b.Property<string>("Whatsapp")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("BlueprintSubmissions");
                });

            modelBuilder.Entity("RedBerryCorporate.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Interest")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("RedBerryCorporate.Models.TblEmployee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ACTUAL_TERMINATION_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("ASSIGNMENT_CATEGORY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ASSIGNMENT_ID")
                        .HasColumnType("int");

                    b.Property<string>("ASSIGNMENT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ASSIGNMENT_STATUS_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<string>("ASSIGNMENT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BADGE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BUSINESS_GROUP_ID")
                        .HasColumnType("int");

                    b.Property<int?>("BankAccountID")
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CONTRACT_END_DATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("CURRENT_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChildCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<long?>("CountryID")
                        .HasColumnType("bigint");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DATE_OF_BIRTH")
                        .HasColumnType("datetime2");

                    b.Property<string>("DegreeHolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EMAIL_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPLOYEE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMPLOYMENT_CATEGORY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EducationId")
                        .HasColumnType("int");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmpDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("EmpRankID")
                        .HasColumnType("bigint");

                    b.Property<int?>("EmployeeType")
                        .HasColumnType("int");

                    b.Property<bool?>("ExcludefromTimesheet")
                        .HasColumnType("bit");

                    b.Property<string>("FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRST_NAME_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FULL_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FULL_NAME_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GRADE_ID")
                        .HasColumnType("int");

                    b.Property<string>("GlobalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HIRE_DATE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HOD")
                        .HasColumnType("int");

                    b.Property<string>("HouseRented")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("INTERNAL_LOCATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idenitification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IncludedInAbsentEmail")
                        .HasColumnType("bit");

                    b.Property<bool?>("IncludedInSupervisorEmail")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSaleman")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSyncWithBMS")
                        .HasColumnType("bit");

                    b.Property<int?>("JOB_ID")
                        .HasColumnType("int");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("JoiningDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LAST_NAME_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LAST_UPDATE_DATE_ASSIGNMENTS")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LAST_UPDATE_DATE_PEOPLE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LOCATION_ID")
                        .HasColumnType("int");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MANAGER_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MARITAL_STATUS_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE_M")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE_SMS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NATIONALITY_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NATIONAL_IDENTIFIER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfChild")
                        .HasColumnType("int");

                    b.Property<string>("OFFICE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OLD_EMPLOYEE_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ORGANIZATION_ID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ORIGINAL_DATE_OF_HIRE")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrgChartID")
                        .HasColumnType("int");

                    b.Property<int?>("PAYROLL_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PAY_BASIS_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PEOPLE_GROUP_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PERSON_ID")
                        .HasColumnType("int");

                    b.Property<int?>("PERSON_TYPE_ID")
                        .HasColumnType("int");

                    b.Property<string>("PHONE_NOS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("POSITION_ID")
                        .HasColumnType("int");

                    b.Property<string>("PRIMARY_FLAG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ProfilePic")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ProfilePicName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RELIGION_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Religion")
                        .HasColumnType("int");

                    b.Property<string>("ReraNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECOND_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECOND_NAME_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SEX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPERVISOR_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("SectID")
                        .HasColumnType("bigint");

                    b.Property<int?>("Session_time")
                        .HasColumnType("int");

                    b.Property<int?>("Shift")
                        .HasColumnType("int");

                    b.Property<string>("SpouseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("THIRD_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("THIRD_NAME_AR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TITLE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Target")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Twitter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("USER_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<bool?>("WFamily")
                        .HasColumnType("bit");

                    b.Property<bool?>("WPS")
                        .HasColumnType("bit");

                    b.Property<string>("WhatsappNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("WorkFromHome")
                        .HasColumnType("bit");

                    b.Property<string>("WorkFromHomeDayWise")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkSite")
                        .HasColumnType("int");

                    b.Property<bool?>("createStatus")
                        .HasColumnType("bit");

                    b.Property<bool?>("updateStatus")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("TblEmployee");
                });

            modelBuilder.Entity("RedBerryCorporate.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("AppIDs")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AppId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AppInspection")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AppWiseRoles")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentList")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DomainUser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EmpId")
                        .HasColumnType("int");

                    b.Property<int?>("InspectRole")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("Language")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.Property<string>("RoleNames")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
