using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RedBerryCorporate.Models
{
    [Table("TblEmployee")]
    public partial class TblEmployee
    {
        [Key]
        public int ID { get; set; }
        public int? PERSON_TYPE_ID { get; set; }
        public string? EMPLOYEE_NUMBER { get; set; }
        public string? OLD_EMPLOYEE_NUMBER { get; set; }
        public int? PAYROLL_ID { get; set; }
        public int? PERSON_ID { get; set; }
        public string? BADGE { get; set; }
        public string? TITLE { get; set; }
        public string? FIRST_NAME { get; set; }
        public string? SECOND_NAME { get; set; }
        public string? THIRD_NAME { get; set; }
        public string? LAST_NAME { get; set; }
        public string? FIRST_NAME_AR { get; set; }
        public string? SECOND_NAME_AR { get; set; }
        public string? THIRD_NAME_AR { get; set; }
        public string? LAST_NAME_AR { get; set; }
        public string? FULL_NAME { get; set; }
        public string? FULL_NAME_AR { get; set; }
        public string? NATIONAL_IDENTIFIER { get; set; }
        public string? MANAGER_FLAG { get; set; }
        public string? SUPERVISOR_NUMBER { get; set; }
        public int? ORGANIZATION_ID { get; set; }
        public int? JOB_ID { get; set; }
        public int? POSITION_ID { get; set; }
        public int? GRADE_ID { get; set; }
        public string? NATIONALITY_CODE { get; set; }
        public string? SEX { get; set; }
        public string? MARITAL_STATUS_CODE { get; set; }
        public string? RELIGION_CODE { get; set; }
        public string? SECT { get; set; }
        public DateTime? DATE_OF_BIRTH { get; set; }
        public DateTime? ORIGINAL_DATE_OF_HIRE { get; set; }
        public DateTime? HIRE_DATE { get; set; }
        public DateTime? ACTUAL_TERMINATION_DATE { get; set; }
        public string? EMAIL_ADDRESS { get; set; }
        public string? MOBILE_SMS { get; set; }
        public string? MOBILE_M { get; set; }
        public int? LOCATION_ID { get; set; }
        public string? OFFICE_NUMBER { get; set; }
        public string? INTERNAL_LOCATION { get; set; }
        public string? CURRENT_FLAG { get; set; }
        public string? PRIMARY_FLAG { get; set; }
        public string? ASSIGNMENT_TYPE { get; set; }
        public string? ASSIGNMENT_CATEGORY { get; set; }
        public string? EMPLOYMENT_CATEGORY { get; set; }
        public int? ASSIGNMENT_ID { get; set; }
        public string? ASSIGNMENT_NUMBER { get; set; }
        public int? PAY_BASIS_ID { get; set; }
        public int? ASSIGNMENT_STATUS_TYPE_ID { get; set; }
        public int? PEOPLE_GROUP_ID { get; set; }
        public string? USER_ID { get; set; }
        public string? USER_NAME { get; set; }
        public string? PHONE_NOS { get; set; }
        public DateTime? CONTRACT_END_DATE { get; set; }
        public DateTime? LAST_UPDATE_DATE_PEOPLE { get; set; }
        public DateTime? LAST_UPDATE_DATE_ASSIGNMENTS { get; set; }
        public int? BUSINESS_GROUP_ID { get; set; }
        public int? DepartmentId { get; set; }
        public int? HOD { get; set; }
        public int? EmployeeType { get; set; }
        public int? Shift { get; set; }
        public int? EducationId { get; set; }
        public DateTime? JoiningDate { get; set; }
        public string? EmergencyContactName { get; set; }
        public string? EmergencyContactPhoneNo { get; set; }
        public string? BloodGroup { get; set; }
        public string? Idenitification { get; set; }
        public string? Address { get; set; }
        public string? FatherName { get; set; }
        public string? MotherName { get; set; }
        public string? SpouseName { get; set; }
        public int? NoOfChild { get; set; }
        public string? ProfilePicName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public bool? IsActive { get; set; }
        public bool? WorkFromHome { get; set; }
        public byte[]? ProfilePic { get; set; }
        public bool? ExcludefromTimesheet { get; set; }
        public bool? WPS { get; set; }
        public string? GlobalId { get; set; }
        public int? WorkSite { get; set; }
        public string? PostalCode { get; set; }
        public string? State { get; set; }
        public long? SectID { get; set; }
        public int? BranchID { get; set; }
        public long? CountryID { get; set; }
        public byte[]? Picture { get; set; }
        public DateTime? EmpDate { get; set; }
        public string? MaritalStatus { get; set; }
        public string? JobType { get; set; }
        public int? ChildCount { get; set; }
        public bool? WFamily { get; set; }
        public string? DegreeHolder { get; set; }
        public long? EmpRankID { get; set; }
        public int? Religion { get; set; }
        public string? HouseRented { get; set; }
        public string? LocationID { get; set; }
        public string? AppID { get; set; }
        public int? BankAccountID { get; set; }
        public int? OrgChartID { get; set; }
        public bool? IsSaleman { get; set; }
        public int? UserID { get; set; }
        public string? AccountNo { get; set; }
        public string? AccountTitle { get; set; }
        public string? IBAN { get; set; }
        public int? StateId { get; set; }
        public int? CityId { get; set; }
        public decimal? Target { get; set; }
        public decimal? Salary { get; set; }
        public int? Session_time { get; set; }
        public string? Photo { get; set; }
        public bool? createStatus { get; set; }
        public bool? updateStatus { get; set; }
        public bool? IsSyncWithBMS { get; set; }
        public string? City { get; set; }
        public string? PersonalEmail { get; set; }
        public string? WorkFromHomeDayWise { get; set; }
        public bool? IncludedInSupervisorEmail { get; set; }
        public bool? IncludedInAbsentEmail { get; set; }
        public string? Bio { get; set; }
        public string? Position { get; set; }
        public string? LinkedIn { get; set; }
        public string? Facebook { get; set; }
        public string? Twitter { get; set; }
        public string? WhatsappNo { get; set; }
        public string? ReraNumber { get; set; }
        public string? Languages { get; set; }
    }
}
